// <auto-generated />
using BookAplikation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookAplikation.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20221129192306_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("BookAplikation.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PublishYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Robert Jordan",
                            CoverType = "Paperback",
                            PublishYear = 1976,
                            Title = "The Eye of the World"
                        },
                        new
                        {
                            Id = 2,
                            Author = "George R.R. Martin",
                            CoverType = "Hardcover",
                            PublishYear = 1988,
                            Title = "A Game of Thrones"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Brandon Sanderson",
                            CoverType = "Hardcover",
                            PublishYear = 1981,
                            Title = "The Way of Kings"
                        },
                        new
                        {
                            Id = 4,
                            Author = "J.R.R. Tolkien",
                            CoverType = "Paperback",
                            PublishYear = 1965,
                            Title = "The Fellowship of the Ring"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Terry Pratchett",
                            CoverType = "Hardcover",
                            PublishYear = 1990,
                            Title = "Sourcery"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Frank Herbert",
                            CoverType = "Electronic",
                            PublishYear = 1975,
                            Title = "Dune"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Scott Lynch",
                            CoverType = "Paperback",
                            PublishYear = 1981,
                            Title = "The Name of the Wind"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Scott Lynch",
                            CoverType = "Hardcover",
                            PublishYear = 1975,
                            Title = "The Lies of Locke Lamora"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Scott Lynch",
                            CoverType = "Electronic",
                            PublishYear = 1977,
                            Title = "Assassin's Apprentice"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
