// <auto-generated />
using System;
using BookAplikation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookAplikation.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20221221194224_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("BookAplikation.Models.Book", b =>
                {
                    b.Property<string>("ISBN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("AvailableBooksInLibrary")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("ECoverType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PublishYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("ISBN");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            ISBN = "0553211765",
                            Author = "Charles Dickens",
                            AvailableBooksInLibrary = 0,
                            Created = new DateTime(2022, 12, 21, 21, 42, 24, 40, DateTimeKind.Local).AddTicks(2521),
                            ECoverType = "Hardcover",
                            PublishYear = 1989,
                            Title = "A Tale of Two Cities",
                            Updated = new DateTime(2022, 12, 21, 21, 42, 24, 40, DateTimeKind.Local).AddTicks(2567)
                        },
                        new
                        {
                            ISBN = "0786275391",
                            Author = "Antoine de Saint-Exupery",
                            AvailableBooksInLibrary = 0,
                            Created = new DateTime(2022, 12, 21, 21, 42, 24, 40, DateTimeKind.Local).AddTicks(2571),
                            ECoverType = "Hardcover",
                            PublishYear = 2005,
                            Title = "The Little Prince",
                            Updated = new DateTime(2022, 12, 21, 21, 42, 24, 40, DateTimeKind.Local).AddTicks(2573)
                        },
                        new
                        {
                            ISBN = "1856134032",
                            Author = "Rowling, J. K.",
                            AvailableBooksInLibrary = 0,
                            Created = new DateTime(2022, 12, 21, 21, 42, 24, 40, DateTimeKind.Local).AddTicks(2576),
                            ECoverType = "Hardcover",
                            PublishYear = 1997,
                            Title = "Harry Potter and The Philosopher's Stone",
                            Updated = new DateTime(2022, 12, 21, 21, 42, 24, 40, DateTimeKind.Local).AddTicks(2579)
                        },
                        new
                        {
                            ISBN = "0451528905",
                            Author = "Miguel de Cervantes",
                            AvailableBooksInLibrary = 0,
                            Created = new DateTime(2022, 12, 21, 21, 42, 24, 40, DateTimeKind.Local).AddTicks(2582),
                            ECoverType = "Paperback",
                            PublishYear = 2003,
                            Title = "Don Quixote",
                            Updated = new DateTime(2022, 12, 21, 21, 42, 24, 40, DateTimeKind.Local).AddTicks(2584)
                        },
                        new
                        {
                            ISBN = "0847980790",
                            Author = "Agatha Christie",
                            AvailableBooksInLibrary = 0,
                            Created = new DateTime(2022, 12, 21, 21, 42, 24, 40, DateTimeKind.Local).AddTicks(2587),
                            ECoverType = "Paperback",
                            PublishYear = 1939,
                            Title = "And Then There Were None",
                            Updated = new DateTime(2022, 12, 21, 21, 42, 24, 40, DateTimeKind.Local).AddTicks(2589)
                        },
                        new
                        {
                            ISBN = "0020198817",
                            Author = "F. Scott Fitzgerald",
                            AvailableBooksInLibrary = 0,
                            Created = new DateTime(2022, 12, 21, 21, 42, 24, 40, DateTimeKind.Local).AddTicks(2592),
                            ECoverType = "Paperback",
                            PublishYear = 1992,
                            Title = "The Great Gatsby",
                            Updated = new DateTime(2022, 12, 21, 21, 42, 24, 40, DateTimeKind.Local).AddTicks(2595)
                        },
                        new
                        {
                            ISBN = "0553213113",
                            Author = "Herman Melville",
                            AvailableBooksInLibrary = 0,
                            Created = new DateTime(2022, 12, 21, 21, 42, 24, 40, DateTimeKind.Local).AddTicks(2598),
                            ECoverType = "Paperback",
                            PublishYear = 1981,
                            Title = "Moby Dick",
                            Updated = new DateTime(2022, 12, 21, 21, 42, 24, 40, DateTimeKind.Local).AddTicks(2600)
                        },
                        new
                        {
                            ISBN = "1400079985",
                            Author = "Leo Tolstoy",
                            AvailableBooksInLibrary = 0,
                            Created = new DateTime(2022, 12, 21, 21, 42, 24, 40, DateTimeKind.Local).AddTicks(2603),
                            ECoverType = "Paperback",
                            PublishYear = 2008,
                            Title = "War and Peace",
                            Updated = new DateTime(2022, 12, 21, 21, 42, 24, 40, DateTimeKind.Local).AddTicks(2605)
                        },
                        new
                        {
                            ISBN = "0451526929",
                            Author = "William Shakespeare",
                            AvailableBooksInLibrary = 0,
                            Created = new DateTime(2022, 12, 21, 21, 42, 24, 40, DateTimeKind.Local).AddTicks(2608),
                            ECoverType = "Paperback",
                            PublishYear = 1998,
                            Title = "Hamlet",
                            Updated = new DateTime(2022, 12, 21, 21, 42, 24, 40, DateTimeKind.Local).AddTicks(2611)
                        },
                        new
                        {
                            ISBN = "0439136350",
                            Author = "Rowling, J. K.",
                            AvailableBooksInLibrary = 0,
                            Created = new DateTime(2022, 12, 21, 21, 42, 24, 40, DateTimeKind.Local).AddTicks(2614),
                            ECoverType = "Hardcover",
                            PublishYear = 1999,
                            Title = "Harry Potter And The Prisoner Of Azkaban",
                            Updated = new DateTime(2022, 12, 21, 21, 42, 24, 40, DateTimeKind.Local).AddTicks(2616)
                        },
                        new
                        {
                            ISBN = "1856136124",
                            Author = "Rowling, J. K.",
                            AvailableBooksInLibrary = 0,
                            Created = new DateTime(2022, 12, 21, 21, 42, 24, 40, DateTimeKind.Local).AddTicks(2619),
                            ECoverType = "Paperback",
                            PublishYear = 1998,
                            Title = "Harry Potter and the Chamber of Secrets",
                            Updated = new DateTime(2022, 12, 21, 21, 42, 24, 40, DateTimeKind.Local).AddTicks(2621)
                        });
                });

            modelBuilder.Entity("BookAplikation.Models.LibraryBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTaken")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookISBN");

                    b.ToTable("LibraryBooks");
                });

            modelBuilder.Entity("BookAplikation.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BooksNotReturnedInTime")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TakenLibraryBooks")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalDebt")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BookAplikation.Models.UserBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BookReturned")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BookTaken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("DaysLate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LibraryBookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LibraryBookId");

                    b.HasIndex("UserId");

                    b.ToTable("UserBooks");
                });

            modelBuilder.Entity("BookAplikation.Models.LibraryBook", b =>
                {
                    b.HasOne("BookAplikation.Models.Book", "Book")
                        .WithMany("LibraryBooks")
                        .HasForeignKey("BookISBN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("BookAplikation.Models.UserBook", b =>
                {
                    b.HasOne("BookAplikation.Models.LibraryBook", "LibraryBook")
                        .WithMany("UserBooks")
                        .HasForeignKey("LibraryBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookAplikation.Models.User", "User")
                        .WithMany("UserBooks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LibraryBook");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookAplikation.Models.Book", b =>
                {
                    b.Navigation("LibraryBooks");
                });

            modelBuilder.Entity("BookAplikation.Models.LibraryBook", b =>
                {
                    b.Navigation("UserBooks");
                });

            modelBuilder.Entity("BookAplikation.Models.User", b =>
                {
                    b.Navigation("UserBooks");
                });
#pragma warning restore 612, 618
        }
    }
}
